# Generated by Django 5.2.3 on 2026-01-23 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_locationpoint_options_route_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationpoint',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='route',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='locationpoint',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('hospital_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Bazar ertəsi'), (2, 'Çərşənbə axşamı'), (3, 'Çərşənbə'), (4, 'Cümə axşamı'), (5, 'Cümə'), (6, 'Şənbə'), (7, 'Bazar')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.DeleteModel(
            name='PushNotificationToken',
        ),
    ]
