# Generated by Django 5.2.3 on 2026-01-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpoint',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='route',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='last_location_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='total_paused_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='locationpoint',
            index=models.Index(fields=['route', 'timestamp'], name='tracking_lo_route_i_1939d1_idx'),
        ),
        migrations.AddIndex(
            model_name='locationpoint',
            index=models.Index(fields=['timestamp'], name='tracking_lo_timesta_514ceb_idx'),
        ),
    ]
