# Generated by Django 5.2.3 on 2026-01-26 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolveyCity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
                ('region_id', models.IntegerField()),
            ],
            options={
                'db_table': 'regions_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolveyDoctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=255)),
                ('ixtisas', models.CharField(blank=True, max_length=255, null=True)),
                ('kategoriya', models.CharField(blank=True, max_length=10, null=True)),
                ('derece', models.CharField(blank=True, max_length=10, null=True)),
                ('cinsiyyet', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('bolge_id', models.IntegerField(blank=True, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('klinika_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doctors_doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolveyHospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=255)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('region_net_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'regions_hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolveyRegion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=255)),
                ('region_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'regions_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationPermissionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('privacy', 'Məxfilik narahatlığı'), ('battery', 'Batareya istehlakı'), ('not_needed', 'İstifadə etmirəm'), ('security', 'Təhlükəsizlik narahatlığı'), ('other', 'Digər')], max_length=20)),
                ('reason_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_permission_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Permission Report',
                'verbose_name_plural': 'Location Permission Reports',
                'ordering': ['-timestamp'],
            },
        ),
    ]
