# Generated by Django 5.2.3 on 2026-01-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_solveycity_solveydoctor_solveyhospital_solveyregion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpermissionreport',
            name='reason',
            field=models.CharField(choices=[('stopped_tracking', 'İzləməni dayandırdım'), ('location_disabled', 'Telefonun konumunu bağladım'), ('privacy', 'Məxfilik narahatlığı'), ('battery', 'Batareya istehlakı'), ('not_needed', 'İstifadə etmirəm'), ('security', 'Təhlükəsizlik narahatlığı'), ('other', 'Digər')], max_length=20),
        ),
    ]
