# Generated by Django 5.2.3 on 2026-01-26 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_alter_locationpermissionreport_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_specialty', models.CharField(blank=True, max_length=255)),
                ('doctor_hospital', models.CharField(blank=True, max_length=255)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visited Doctor',
                'verbose_name_plural': 'Visited Doctors',
                'ordering': ['-visit_date'],
                'unique_together': {('user', 'doctor_id', 'visit_date')},
            },
        ),
    ]
