# Generated by Django 5.2.3 on 2026-01-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_visiteddoctor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visiteddoctor',
            unique_together=set(),
        ),
    ]
