# Generated by Django 5.0.10 on 2026-02-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_alter_visiteddoctor_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Dərman adı')),
                ('name_az', models.CharField(blank=True, max_length=255, verbose_name='Dərman adı (Azərbaycan)')),
                ('description', models.TextField(blank=True, verbose_name='Qısa təsvir')),
                ('annotation', models.TextField(help_text='2 A4 vərəqi boyda məlumat', verbose_name='Annotasiya (tərkib, istifadə qaydaları)')),
                ('active_ingredient', models.CharField(blank=True, max_length=500, verbose_name='Aktiv tərkib')),
                ('dosage', models.CharField(blank=True, max_length=255, verbose_name='Doza')),
                ('indications', models.TextField(blank=True, verbose_name='Göstərişlər')),
                ('contraindications', models.TextField(blank=True, verbose_name='Qadağalar')),
                ('side_effects', models.TextField(blank=True, verbose_name='Yan təsirlər')),
                ('storage_conditions', models.CharField(blank=True, max_length=255, verbose_name='Saxlama şəraiti')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='İstehsalçı')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='Barkod')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/', verbose_name='Şəkil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dərman',
                'verbose_name_plural': 'Dərmanlar',
                'ordering': ['order', 'name'],
            },
        ),
    ]
