# Generated by Django 5.0.10 on 2026-02-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolveyMedicine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=250)),
                ('med_full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('med_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('komissiya', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'medical',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='solvey_id',
            field=models.IntegerField(blank=True, help_text='Solvey database-dəki dərman ID-si', null=True, unique=True, verbose_name='Solvey Database ID'),
        ),
    ]
