# Generated by Django 5.2.3 on 2026-02-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_solveymedicine_medicine_solvey_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='last_battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationpermissionreport',
            name='reason',
            field=models.CharField(choices=[('location_started', 'Konum paylaşımı başladı'), ('stopped_tracking', 'İzləməni dayandırdım'), ('location_disabled', 'Telefonun konumunu bağladım'), ('internet_disabled', 'İnterneti bağladım'), ('privacy', 'Məxfilik narahatlığı'), ('battery', 'Batareya istehlakı'), ('not_needed', 'İstifadə etmirəm'), ('security', 'Təhlükəsizlik narahatlığı'), ('other', 'Digər')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='solveymedicine',
            table='medicine_medical',
        ),
    ]
