# Generated by Django 5.2.3 on 2026-04-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitlogprofile',
            name='custom_foods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fitlogprofile',
            name='diary_entries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
