# Generated by Django 5.2.3 on 2026-04-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlog', '0002_fitlogprofile_custom_foods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitlogprofile',
            name='recipes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fitlogprofile',
            name='water_entries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
